### PR TITLE
I was able to get the module to pull rates

### PR DESCRIPTION
**Pull request by mdlutz24**
This needs to be run with the latest -dev of commerce shipping, and I still have some issues, but it is at least pulling rates now, I have a bunch more work to do.

### CODE REVIEW

**Comment by ReplicaObscura** [comment]
This is awesome, thanks for submitting! Going to test this out tonight and see what's left to be done.

**Comment by ReplicaObscura** [comment]
@mdlutz24 Even though there is more work to be done, I'm good with merging this PR as-is so that we have a common base to continue working off of.

I'll create issues in the queue for the things I'm working on so that you can be aware and we hopefully won't duplicate too much of each others' work if you're actively making progress on this too.

Thanks again for the PR, by the way!

**Comment by mdlutz24** [comment]
Thanks, Ben.  
I am going to be actively working on this now that shipping has gotten where it needs to be.  I will try to coordinate with you.  My first task is going to be figuring out setting the packages correctly, and then seeing about adding discoverable traits for hazardous materials and dry ice, which I need for my project.

**Comment by ReplicaObscura** [comment]
Sounds great! I have a need for traits such as that as well.

For now I'll focus on other aspects of the module and let you work on that one without me getting in your way. I'll start creating issues for these couple things I know about so far so we can assign things as needed.

**Pull request merged**
